arb-dir: lib/l10n
template-arb-file: app_en.arb # ここに設定した言語が基本的に使用される言語となります。
# output-class: L10n # 任意の設定値 設定した値で多言語化対応文字列を呼び出すことができる。設定しない場合は、「AppLocalizations.XXX」で呼び出します。
output-localization-file: app_localizations.dart
